version: "3.9"
services:
recon:
build: .
container_name: recon-toolkit
ports:
- "5000:5000"
volumes:
- ./jobs:/app/jobs # persistent outputs
- ./logs:/app/logs # persistent command log
environment:
- PYTHONUNBUFFERED=1
restart: unless-stopped # optional
